-- Schema obsoleto, ver supabase/migrations/ pra estado real
-- Removido em 2026-04-28: descrevia Supabase Auth + RLS, mas o projeto usa
-- Clerk + Neon Postgres sem RLS. Estado real do schema vive nas migrations
-- aplicadas em supabase/migrations/*.sql.
