#!/usr/bin/env node
// Gera lib/ascii-texts.ts com strings figlet em build time.
// Roda: node scripts/gen-ascii.mjs (ou: bun run gen:ascii)

import figlet from "figlet"
import { writeFile, mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"

// Texto -> font figlet escolhida.
// ANSI Shadow ganhou em todos os testes: 3D com sombra, alta legibilidade,
// vibe brutalist que combina com o resto do projeto (pixel font + shadow brutal).
const TEXTS = {
  ART_AUTOPILOT: { text: "AUTOPILOT", font: "ANSI Shadow" },
  ART_BLOG: { text: "BLOG", font: "ANSI Shadow" },
  ART_AI_POWER: { text: "AI POWER", font: "ANSI Shadow" },
  ART_GERAR: { text: "GERAR", font: "ANSI Shadow" },
  ART_SEO_92: { text: "SEO 92", font: "ANSI Shadow" },
}

const OUT_PATH = resolve(process.cwd(), "lib/ascii-texts.ts")

let out = "// AUTO-GENERATED by scripts/gen-ascii.mjs — do not edit by hand.\n"
out += "// Re-run with: bun run gen:ascii\n\n"

for (const [name, { text, font }] of Object.entries(TEXTS)) {
  const ascii = figlet.textSync(text, { font })
  // trim trailing whitespace per line, mantem layout
  const cleaned = ascii
    .split("\n")
    .map((l) => l.replace(/\s+$/, ""))
    .join("\n")
    .replace(/^\n+|\n+$/g, "")
  out += `// ${text} (${font})\n`
  out += `export const ${name} = ${JSON.stringify(cleaned)};\n\n`
}

await mkdir(dirname(OUT_PATH), { recursive: true })
await writeFile(OUT_PATH, out)
console.log(`OK: ${OUT_PATH} gerado (${Object.keys(TEXTS).length} artes)`)
